#!/usr/bin/perl
use EPrints;
use strict;

my $repository = EPrints->new->current_repository;
exit( 0 ) unless( defined $repository );
my $xml = $repository->xml;

my $eprintid = $repository->param("id");
my $eprint = EPrints::DataObj::EPrint->new($repository, $eprintid);

my $user = $repository->current_user;

if ( $eprint->value( "eprint_status" ) eq "inbox" )
{
	if ($eprint->value( "validation_status" ) eq "error" )
	{
		print $xml->to_string( $repository->html_phrase( "premiere_preview:invalid" ) );
	}
	else
	{
		print $xml->to_string( $repository->html_phrase( "premiere_preview:private" ) );
	}
	return;
}


my $first_document = ($eprint->get_all_documents())[0];

if (not $first_document)
{
	print $xml->to_string( $repository->html_phrase( "premiere_preview:no_documents" ) );
	return;
}

if ( $repository->call("can_user_view_document", $first_document, $user) eq "ALLOW" )
{
	my $div = $xml->create_document_fragment;
	$div->appendChild( $eprint->render_citation("premiere_preview_document_list") );
	print '<iframe id="premiere_preview_area" scrolling="no" src=""> </iframe>';
	print $xml->to_string( $div );
}
else
{
	print $xml->to_string( $repository->html_phrase( "premiere_preview:denied" ) );
}

