#!/bin/perl

use EPrints;

use strict;



# If you want to modify the list that is rendered please consult
# archives/ARCHIVEID/cfg/cfg.d/resourcemanager.pl.

my $session = new EPrints::Session;
exit unless defined $session;

my @response;

my $user = $session->current_user;
unless( defined $user )
{
	my $response->appendChild( $session->html_phrase( 'cgi/resourcemanager:must_be_loggedin' ) );
	$session->terminate;
	print EPrints::XML::to_string( $response, undef, 1 );
	exit;
}


my $filter = $session->plugin( "ResourceManagerFilter" );
my $list = get_filtered_item_list($session, $filter);

push(@response, EPrints::XML::to_string($filter->render_filter_control( $list ), undef, 1));
push(@response, EPrints::XML::to_string(render_item_list($session, $list), undef, 1));

$session->terminate;

use CGI qw(:standard);
print header('application/json');

use JSON;
print encode_json \@response;

sub get_filtered_item_list
{
	my( $session, $filter ) = @_;

	my $user = $session->current_user;
	my $ds = $session->get_dataset( 'eprint' );
# mrt - cut since there are no shared edit permissions yet
#	my $user_owned_eprints = $user->get_owned_eprints( $eprint_ds );
	my $search = EPrints::Search->new(
		dataset => $ds,
		session => $session,
	);

	$search->add_field( $ds->get_field("userid"), $user->id);

	if( defined $filter )
	{
		foreach my $field ( @{$session->get_repository->get_conf( 'resourcemanager_filter_fields' )} )
		{
			my @values = @{$filter->get_current_filter_values( $field )};
			if( scalar @values )
			{
				$search->add_field( $ds->get_field( $field ), join( ' ', @values ), "IN", "ALL");
			}
		}
	}

	my $filtered_eprint_list = $search->perform_search;

# mrt - cut since there are no shared edit permissions yet
#	$filtered_eprint_list = $filtered_eprint_list->intersect( $user_owned_eprints, "title" );

	return $filtered_eprint_list->reorder( "-lastmod" );
}

sub render_item_list
{
	my( $session, $eprint_list ) = @_;
	my $item_list = $session->make_doc_fragment;

	if( !$eprint_list->count )
	{
		$item_list->appendChild( $session->html_phrase( 'cgi/resourcemanager:no_resources' ) );
	}
	else
	{
		my %info;
		$info{dom} = $item_list;

	
		$eprint_list->map( sub{
			my( $session, $dataset, $eprint, $info ) = @_;
					
			my $url;
			if( $eprint->get_value( 'eprint_status' ) eq 'archive' )
			{
				$url = $eprint->get_url;
			}
			else
			{
				$url = $session->get_repository->get_conf( 'rel_path' ).'/cgi/users/home?screen=EPrint::Summary&eprintid='.$eprint->get_id;
			}
			my $container = $session->make_element( "div", id => "manageable_id_".$eprint->get_id, class => "ep_manageable" );
			$container->appendChild( $eprint->render_citation( 'manageable', url => $url ) );
			$info->{dom}->appendChild( $container );
		}, \%info );
	}

	return $item_list;
}

