#!/usr/bin/perl

use EPrints;

use strict;

my $session = EPrints::Session->new();

my $content = "text/xml";
$session->send_http_header( content_type=>$content );

print <<END;
<?xml version="1.0" encoding="UTF-8" ?>
END

my $js_prefix = $session->param( "jsvar" );
my $fieldname = $session->param( "fieldname" );

unless( defined $js_prefix && defined $fieldname )
{
        print "<p>Wrong arguments</p>";
        $session->terminate;
        return;
}

# yes this is a bit hacky but safer
unless( $fieldname eq 'raw_keywords' || $fieldname eq 'courses' )
{
        print "<p>Wrong arguments</p>";
        $session->terminate;
        return;
}

my $userid = $session->current_user->get_id;

my $sql = "SELECT DISTINCT $fieldname, count($fieldname) FROM eprint_$fieldname WHERE eprintid IN ( SELECT eprintid FROM eprint WHERE userid='$userid' ) group by $fieldname order by count($fieldname) desc LIMIT 20;";

my $sth = $session->get_database->prepare( $sql );
$session->get_database->execute( $sth , $sql );
my $done_any = 0;

while( my( $k ) = $sth->fetchrow_array )
{
		my $safek = $k;
		$safek =~ s/'/\\'/g;
                print "<a href=\"#\" onclick=\"$js_prefix.initTag( '$safek' );return false;\">$k</a>&nbsp;";
                $done_any++;
}

unless( $done_any )
{
        print "<p>No tag found</p>";
}

$session->terminate;
return;

