#!/usr/bin/perl

use strict;

use EPrints;

my $repo = EPrints->new()->current_repository();

my $database = $repo->get_database();

my ( $query, $sql, $sth );

if($repo->param("type") eq "user")
{
	$query = $database->quote_value($repo->param("query").'%');
	$sql = "SELECT DISTINCT name_given, name_family, username FROM user WHERE name_given LIKE $query OR name_family LIKE $query OR username LIKE $query";

	$sth = $repo->get_database->prepare( $sql );
	$repo->get_database->execute( $sth , $sql );

	print "<ul>";
	while( my( $given, $family, $username ) = $sth->fetchrow_array )
	{
		print "<li><span class='informal'>$given $family (</span>$username<span class='informal'>)</span></li>";
	}
	print "</ul>";
}

if($repo->param("type") eq "department")
{
	$query = $database->quote_value($repo->param("query").'%');
	$sql = "SELECT DISTINCT dept FROM user WHERE dept LIKE $query "; 

	$sth = $repo->get_database->prepare( $sql );
	$repo->get_database->execute( $sth , $sql );

	print "<ul>";
	while( my( $dept ) = $sth->fetchrow_array )
	{
		print "<li>$dept</li>";
	}
	print "</ul>";
}
